language: python
dist: xenial
sudo: false
python:
  - "3.6"
  - "2.7"
env:
  - DJANGO="Django>=1.11,<2"
#   - DJANGO="Django>=2.0"
# matrix:
#   exclude:
#   - python: '2.7'
#     env: DJANGO="Django>=2.0"

install:
  - pip install -r requirements.txt
  - pip install $DJANGO
  - pip install pytest-cov
script:
  - py.test --junitxml=results.xml --cov=./
  - bash <(curl -s https://codecov.io/bash)
